version: '3.6'

networks:
  user-activity-network:
    name: user-activity-network
    driver: bridge

services:

  php:
    build: './docker/php/'
    container_name: user-activity.php
    networks:
      - user-activity-network
    volumes:
      - ./:/var/www/html/

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - user-activity-network
    ports:
      - '8005:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/user-activity.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mariadb:
    image: mariadb:10.4.17
    container_name: user-activity.mariadb
    restart: always
    networks:
      - user-activity-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sdEd-Fds4-DneR-Q3sx
      MYSQL_DATABASE: user_activity
      MYSQL_HOST: mariadb
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]